import type { Metadata } from "next";
import {
  Oswald,
  Geist,
  Geist_Mono,
  Pixelify_Sans,
  Inter,
} from "next/font/google";
import "./globals.css";

const GameFont = Pixelify_Sans({
  subsets: ["latin"],
  variable: "--font-game",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
});

export const metadata: Metadata = {
  title: "E-Learning App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${oswald.variable} ${GameFont.variable} ${inter.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
